## 1. Understand Broadcasting in Your Own Words
    In a markdown cell (or a comment), write what you understand by the term “broadcasting” in NumPy. Including the example.
    Objective: 
    To ensure conceptual clarity of broadcasting, which is fundamental for efficient NumPy operations.


In [3]:
 ## Broadcasting in Numpy is a powerful mechanism that allows operations to be performed based on arrays of different shapes

## 2. Apply Broadcasting with Scalar
    Create a 3x3 array filled with numbers from 1 to 9. Add 10 to the entire array using broadcasting and Print the updated array.
    
    Objective: 
    
    See how NumPy automatically applies operations without loops.


In [6]:
import numpy as np

In [12]:
scalar_array = np.random.randint(1,9,(3,3))
scalar_array

array([[5, 5, 1],
       [4, 5, 5],
       [6, 8, 4]])

In [14]:
updated_scalar_matrix = scalar_array + 10

In [18]:
print('Matrix after adding 10:\n',updated_scalar_matrix)

Matrix after adding 10:
 [[15 15 11]
 [14 15 15]
 [16 18 14]]


## 3. Broadcasting with Two Arrays
    Create a 3x1 array (column vector) and a 1x3 array (row vector), then perform an addition operation between them.
    	Example: a = np.array([[1], [2], [3]])
        b = np.array([[10, 20, 30]])
    
    Objective: 
    
    Visualize how NumPy stretches arrays to match dimensions.


In [21]:
a = np.array([[1], [2], [3]])
b = np.array([[10, 20, 30]])

In [23]:
c = a + b

In [25]:
print('Array Broadcasting Addtion:\n',c)

Array Broadcasting Addtion:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## 4. Use np.where() for Conditional Selection
    Create a 1D array of values from 1 to 10. Use np.where() to replace:
    All even numbers with 0
    All odd numbers with 1
    
    Objective: 
    
    Practice conditional replacement using vectorized logic.


In [42]:
conditional = np.arange(1,11)

In [44]:
even_odd = np.where(conditional % 2 == 0,0,1)

In [46]:
even_odd

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

## 5. Create a Mask Using Multiple Conditions
    Create an array of values from 10 to 30. Use boolean masking to filter elements:
    Greater than 15 AND divisible by 3
    
    Objective: 
    
    Get comfortable with combining conditions using & and |.
    


In [49]:
mask_array = np.arange(10,31)

In [51]:
mask_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [57]:
mask_boolean = ((mask_array > 15) & (mask_array % 3))

In [59]:
print(mask_boolean)

[0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0]


## 6. Use np.where() with Two Arrays
    Create two arrays of 5 elements each.
    Use np.where() to pick elements from array A where values in array B are greater than 5, otherwise pick from B.
    
    Objective: 
    
    Learn conditional element-wise selection.


In [70]:
a = np.array([10,20,30,40,50])
b = np.array([3, 6, 1, 8, 5])

In [72]:
conditional = np.where(b > 5,a,b)

In [74]:
print(conditional)

[ 3 20  1 40  5]


## 7. Create a Custom Grading System
    Generate an array of 10 random marks between 0 and 100. Use np.where() to assign grades:
    'A' for marks >= 75
    'B' for 50–74
    'C' for below 50
    Hint: Use np.select() or chain np.where()
    
    Objective: 
    
    Apply broadcasting and conditional logic to real-world-style data


In [88]:
marks = np.random.randint(0,100,10)

In [90]:
marks

array([65, 69, 26, 16, 34, 89, 50, 94, 49, 42])

In [100]:
assign1 = np.where(marks >= 75,'A',(
          np.where(marks >= 50,'B','C')))

In [106]:
print('Marks:',marks)
print('Grades:',assign1)

Marks: [65 69 26 16 34 89 50 94 49 42]
Grades: ['B' 'B' 'C' 'C' 'C' 'A' 'B' 'A' 'C' 'C']


In [ ]:
using np.select

In [114]:
condition = [marks >=75,(marks >=50)&(marks <75),marks<50]

In [116]:
choice = ['A','B','C']

In [118]:
assign2 = np.select(condition,choice)

In [120]:
print('Marks:',marks)

Marks: [65 69 26 16 34 89 50 94 49 42]


In [122]:
print('Grades:',assign2)

Grades: ['B' 'B' 'C' 'C' 'C' 'A' 'B' 'A' 'C' 'C']


## 8. Compare Two Arrays Element-wise
    Create two arrays of shape (3, 3). Print a boolean array that shows where the elements are equal.
    
    Objective: 
    
    Learn to compare arrays efficiently and use comparison results.


In [125]:
arr1 = np.random.randint(1,9,(3,3))

In [127]:
arr1

array([[7, 6, 2],
       [3, 3, 8],
       [1, 7, 5]])

In [129]:
arr2 = np.random.randint(1,9,(3,3))

In [131]:
arr2

array([[6, 7, 4],
       [2, 3, 6],
       [5, 7, 6]])

In [133]:
arr1 == arr2

array([[False, False, False],
       [False,  True, False],
       [False,  True, False]])

## 9. Use np.any() and np.all()
    On a random 3x3 integer array:
    Check if any value is greater than 90.
    Check if all values are positive.
    Delete the element at index 3.
    
    Objective: 
    
    Use aggregation functions to evaluate conditions across an array.
    


In [160]:
arr3 = np.random.randint(0,101,(3,3))

In [162]:
arr3

array([[100,  75,   4],
       [  4,  40,  78],
       [ 45,  33,   1]])

In [164]:
value_90 = np.any(arr3>90)
value_90

True

In [166]:
positive = np.all(arr3>0)

In [168]:
positive

True

In [170]:
dele = arr3.flatten()

In [172]:
dele

array([100,  75,   4,   4,  40,  78,  45,  33,   1])

In [174]:
delete_3rd = np.delete(arr3,3)

In [176]:
delete_3rd

array([100,  75,   4,  40,  78,  45,  33,   1])