## 1. What is NumPy? Why is it used in Python?
    Objective:
    Understand the basics of NumPy and its significance in scientific computing.


## 2. Install NumPy in your Python environment.
    Objective:
    	Install the NumPy library to begin using it in your projects.


## 3. Create a simple 1D NumPy array containing the values 10, 20, 30, 40, and 50.
    Objective:
    	Learn how to create and work with basic NumPy arrays.


In [13]:
import numpy as np
simple_array = np.array([10,20,30,40,50])

## 4. Create an array on your own using Numpy and print the shape and data type of the array you created.
    Objective:
    	Understand how to access the attributes of a NumPy array, such as its shape and data type.


In [22]:
own_array = np.array([[1,2,3,4],[5,6,7,8]])
print(own_array)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
print('The Shape of array is',np.shape(own_array))

The Shape of array is (2, 4)


In [20]:
print('The Data type of array is ',own_array.dtype)

The Data type of array is  int32


## 5. What are the advantages of using NumPy arrays over Python lists?
    Objective:
    	Explore the key differences between NumPy arrays and Python lists.


## 6. Create a 2D NumPy array (matrix) of size 2x3 with values from 1 to 6.
    Objective:
    	Understand how to create multi-dimensional arrays and how they work in NumPy.


In [40]:
twod_array = np.array([[1,2,3],[4,5,6]])
print(twod_array)

[[1 2 3]
 [4 5 6]]


## 7. Create a 3x3 identity matrix using NumPy.
    Objective:
    	Learn how to create special types of matrices like the identity matrix using NumPy functions.

In [45]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8. What is the difference between the np.array() function and np.arange() function in NumPy?
    Objective:
    	Understand the difference between np.array() and np.arange() for creating NumPy arrays.


## 9. Create a NumPy array with values from 1 to 100 with a step of 5 using np.arange().
    
    Objective:
    	Learn to use np.arange() to generate sequences of numbers in a specific range.

In [53]:
arrar_arange = np.arange(1,100,5)

In [55]:
print(arrar_arange)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
