## 1. Create two 1D arrays
    One containing multiples of 3 in variable (a)
    One containing multiples of 5 in variable (b)
    Objective: 
    Practice generating specific patterns in arrays.


In [4]:
import numpy as np
a = np.arange(3,31,3)
b = np.arange(5,51,5)
print('Multiples of 3:',a)
print('Multiples of 5:',b)

Multiples of 3: [ 3  6  9 12 15 18 21 24 27 30]
Multiples of 5: [ 5 10 15 20 25 30 35 40 45 50]


## 2. Perform Arithmetic Operations
    Using the arrays a and b from the previous task, perform element-wise addition, subtraction, multiplication, and division.
    
    Objective: 
    
    Understand broadcasting and arithmetic operations in NumPy.


In [7]:
a

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [9]:
b

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [13]:
np.add(a,b)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [15]:
np.subtract(a,b)

array([ -2,  -4,  -6,  -8, -10, -12, -14, -16, -18, -20])

In [17]:
np.multiply(a,b)

array([  15,   60,  135,  240,  375,  540,  735,  960, 1215, 1500])

In [19]:
np.divide(a,b)

array([0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6])

## 3. Statistical Summary
        For the arrays a and b (created in previous questions or create a new one):
        Find and print the Mean (average)
        Find and print the Median
        Find and print the Mode
        Find and print the Range (Max - Min)
        Find and print the Standard Deviation
        Find and print the Variance
        Find and print the Sum

    Objective: 
    
    Explore a variety of basic statistical functions using NumPy to gain deeper knowledge.


In [33]:
#mean
print(np.mean(a))
print(np.mean(b))

16.5
27.5


In [37]:
#median
print(np.median(a))
print(np.median(b))

16.5
27.5


In [45]:
#Range
print(np.amax(a))
print(np.amax(b))

30
50


In [49]:
#Range - min
print(np.amin(a))
print(np.amin(b))

3
5


In [53]:
#Standard deviation
print(np.std(a))
print(np.std(b))

8.616843969807043
14.361406616345072


In [55]:
#Varience
print(np.var(a))
print(np.var(b))

74.25
206.25


In [59]:
print(np.sum(a))
print(np.sum(b))

165
275


## 4. Use flip() to Reverse
    Create a 1D NumPy array with values from 10 to 50 using np.arange(). Reverse the array using np.flip().
    
    Objective: 
    
    Understand array flipping and reversing.


In [66]:
flip_array = np.arange(10,51)
flip_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [68]:
np.flip(flip_array,axis = 0)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

## 5. Reverse Without flip()
    Achieve the same reversed array without using np.flip().
    
    Objective: 
    
    Reinforce knowledge on slicing techniques in NumPy.


In [71]:
flip_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [79]:
flip_array[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

## 6. Boolean Indexing
    Using the reversed array (from the previous task or a newly created one), do the following:
        Create a boolean array where each value checks whether the element is greater than 30.
        Print the boolean array (it will contain only True or False values).
        Use this boolean array to filter out only the elements that are greater than 30 from the original array.

    Objective: 
    
    Learn how to filter and mask data using boolean arrays.


In [84]:
flip_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [86]:
boolean_array = flip_array > 30
print(boolean_array)

[False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]


In [88]:
filter_array = flip_array[boolean_array]

In [90]:
filter_array

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50])

## 7. Conditional Replacement
    Replace all even numbers in the reversed array (or a newly created array) with -1 and print the modified array.
    
    Objective: 
    
    Learn how to apply conditional logic to modify arrays in NumPy.



In [95]:
flip_array[flip_array % 2 == 0] = -1

In [97]:
flip_array

array([-1, 11, -1, 13, -1, 15, -1, 17, -1, 19, -1, 21, -1, 23, -1, 25, -1,
       27, -1, 29, -1, 31, -1, 33, -1, 35, -1, 37, -1, 39, -1, 41, -1, 43,
       -1, 45, -1, 47, -1, 49, -1])

## 8. Random 2D Array Transformation
    Generate a 2D array of shape (3, 3) with random integers between 10 and 99. Transpose the array and then flatten it into a 1D array.
    
    Objective: 
    
    Practice manipulating the shape of NumPy arrays.


In [102]:
twod_array = np.random.randint(10,100,size = (3,3))

In [104]:
print(twod_array)

[[82 46 20]
 [20 60 20]
 [26 51 92]]


## 9. Modify Array Elements
    Take the flattened array from Question 8.
    Insert the value 99 at index 2.
    Append the value 100 at the end.
    Delete the element at index 3.
    
    Objective: 
    
    Understand how to modify NumPy arrays using insert, append, and delete operations.
    


In [107]:
insert = np.insert(twod_array,2,99)
insert

array([82, 46, 99, 20, 20, 60, 20, 26, 51, 92])

In [109]:
append = np.append(twod_array,100)

In [111]:
append

array([ 82,  46,  20,  20,  60,  20,  26,  51,  92, 100])

In [113]:
delete = np.delete(twod_array,3)

In [115]:
delete

array([82, 46, 20, 60, 20, 26, 51, 92])

## 10. Array Iteration
    Create a 2D NumPy array of shape (2, 3) with any integers.
    Iterate through the array using a basic for loop.
    Then, iterate using np.nditer().
    
    Objective: 
    
    Explore different ways of traversing NumPy arrays.


In [122]:
arr2d = np.array([[1,2],[3,4],[5,6]])

In [124]:
arr2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
for i in arr2d:
    for j in i:
        print(j)

1
2
3
4
5
6


In [128]:
for i in np.nditer(arr2d):
    print(i)



1
2
3
4
5
6


## 11. Operations on Random Float Arrays
    Generate two 1D arrays (length 5 each) with random float numbers between 1 and 10.
    Perform element-wise operations: +, -, *, /, %, //.
    Apply mathematical functions: np.sqrt(), np.exp(), np.sin(), np.log().
    
    Objective: 
    
    Get hands-on with math operations and functions in NumPy.



In [139]:
arr1 = np.random.uniform(1,10,5)
arr2 = np.random.uniform(1,10,5)

In [141]:
print(arr1)
print(arr2)

[5.5916506  6.40500078 8.15932825 6.46411298 4.21473385]
[1.15725099 2.8705789  8.57220607 7.52840497 2.09527329]


In [145]:
#element wise operations
add = arr1 + arr2
print(add)

[ 6.74890159  9.27557968 16.73153431 13.99251795  6.31000715]


In [147]:
sub = arr1 - arr2
print(sub)

[ 4.43439961  3.53442188 -0.41287782 -1.06429199  2.11946056]


In [149]:
mul = arr1 * arr2
print(mul)

[ 6.47094319 18.38606008 69.94344311 48.6644603   8.83101928]


In [151]:
div = arr1 / arr2
print(div)

[4.83183912 2.23125753 0.95183529 0.85862982 2.01154373]


In [153]:
mod = arr1 % arr2
print(mod)

[0.96264665 0.66384298 8.15932825 6.46411298 0.02418727]


In [155]:
floor_div = arr1 // arr2
print(floor_div)

[4. 2. 0. 0. 2.]


In [157]:
sqrt_arr1 = np.sqrt(arr1)
print(sqrt_arr1)

[2.36466712 2.5308103  2.85645379 2.54246199 2.0529817 ]


In [ ]:
exp_arr1 = np.exp(arr1)
print
sin_arr1 = np.sin(arr1)
log_arr1 = np.log(arr1)