## 1. Explain Data Analysis in Your Own Words.
    📓 Use a markdown cell to describe what Data Analysis means to you.


>- Data Analysis is a process of collecting,organising,interpreting and visualizing data to uncover useful information, patterns, and insights. 


## 2. Generate Arrays of Different Dimensions.
    Generate five NumPy arrays using np.arange():
    0D array (a single value)
    1D array (e.g., 0 to 4)
    2D array (reshape a 1D array into 2x3)
    3D array (create a 2x2x2 cube)
    4D array (bonus!)


In [19]:
import numpy as np
zerodim_array = np.array(42)
zerodim_array

array(42)

In [21]:
onedim_array = np.arange(5)
onedim_array

array([0, 1, 2, 3, 4])

In [39]:
twodim_array = np.arange(6).reshape(2,3)
twodim_array

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
threedim_array = np.arange(8).reshape(2,2,2)
threedim_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
fourdim_array = np.arange(8).reshape(2,2,1,2)
fourdim_array

array([[[[0, 1]],

        [[2, 3]]],


       [[[4, 5]],

        [[6, 7]]]])

## 3. Print the datatype, shape, size, and dimension of each of the above arrays
    Use .dtype, .shape, .size, and .ndim.


In [50]:
print('1D Array:',onedim_array.dtype)
print('1D Array:',np.shape(onedim_array))
print('1D Array:',np.size(onedim_array))
print('1D Array:',np.ndim(onedim_array))

1D Array: int32
1D Array: (5,)
1D Array: 5
1D Array: 1


In [52]:
print('2D Array:',twodim_array.dtype)
print('2D Array:',np.shape(twodim_array))
print('2D Array:',np.size(twodim_array))
print('2D Array:',np.ndim(twodim_array))

2D Array: int32
2D Array: (2, 3)
2D Array: 6
2D Array: 2


In [54]:
print('3D Array:',threedim_array.dtype)
print('3D Array:',np.shape(threedim_array))
print('3D Array:',np.size(threedim_array))
print('3D Array:',np.ndim(threedim_array))

3D Array: int32
3D Array: (2, 2, 2)
3D Array: 8
3D Array: 3


In [56]:
print('4D Array:',fourdim_array.dtype)
print('4D Array:',np.shape(fourdim_array))
print('4D Array:',np.size(fourdim_array))
print('4D Array:',np.ndim(fourdim_array))

4D Array: int32
4D Array: (2, 2, 1, 2)
4D Array: 8
4D Array: 4


## 4. Generate a NumPy Array Using Random Function.
    Use np.random.rand() to generate a 1D array of 5 random values.


In [61]:
random_array = np.random.rand(5)
print(random_array)

[0.20750329 0.35211222 0.94562458 0.15096459 0.51302847]


## 5. Access & Slice Elements
    Using the array you created in Question 4 (a 1D array of 5 random values generated with np.random.rand()):
    Print the element at the second index.
    Print the first three elements.


In [65]:
random_array[2]

0.9456245754601531

In [67]:
random_array[:3]

array([0.20750329, 0.35211222, 0.94562458])

## 6. Create a 2D Array with Random Numbers.
    Use np.random.randint() to generate a 2D array of shape 3x3 with values from 1 to 100.


In [72]:
dim2D = np.random.randint(1,101,size = (3,3))
print(dim2D)

[[94 72 37]
 [11 65 50]
 [90 63 63]]


## 7. Create Evenly Spaced Values.
    Create an array of 5 evenly spaced values between 0 and 1 using np.linspace().


In [77]:
evenly_spaces = np.linspace(0,1,5)
evenly_spaces

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

 ## 8.Create a 3x3 Matrix:
    Filled with ones
    With ones only on the diagonal
    Filled with zeros
    Tip: Use np.ones(), np.eye(), and np.zeros().


In [80]:
ones_matrix = np.ones((3,3))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
diagnol_ones = np.eye(3)
diagnol_ones

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
zero_matrix = np.zeros((3,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])